export const CATEGORY_LIBRARY = {
  categories: [
    {
      id: "instagram",
      label: "Instagram",
      icon: "ShareIcon",
      formats: [
        {
          id: "insta_post",
          name: "Instagram Post",
          width: 1080,
          height: 1080,
          ratio: "1:1",
          platform_type: "instagram_post_square",
          color: "#E4405F",
          key: "instagram",
          cat: "instagram",
        },
        {
          id: "insta_story",
          name: "Instagram Story",
          width: 1080,
          height: 1920,
          ratio: "9:16",
          platform_type: "instagram_story",
          color: "#E4405F",
          key: "instagram",
          cat: "instagram",
        },
      ],
    },
    {
      id: "youtube",
      label: "YouTube",
      icon: "ShareIcon",
      formats: [
        {
          id: "youtube_thumbnail",
          name: "YouTube Thumbnail",
          width: 1280,
          height: 720,
          ratio: "16:9",
          platform_type: "youtube_thumbnail",
          color: "#FF0000",
          key: "youtube",
          cat: "youtube",
        },
      ],
    },
    {
      id: "facebook",
      label: "Facebook",
      icon: "ShareIcon",
      formats: [
        {
          id: "facebook_post",
          name: "Facebook Post",
          width: 1200,
          height: 630,
          ratio: "1.91:1",
          platform_type: "facebook_post",
          color: "#1877F2",
          key: "facebook",
          cat: "facebook",
        },
      ],
    },
    {
      id: "whatsapp",
      label: "WhatsApp",
      icon: "ShareIcon",
      formats: [
        {
          id: "whatsapp_status",
          name: "WhatsApp Status",
          width: 1080,
          height: 1920,
          ratio: "9:16",
          platform_type: "whatsapp_status",
          color: "#25D366",
          key: "whatsapp",
          cat: "whatsapp",
        },
      ],
    },
    {
      id: "linkedin",
      label: "LinkedIn",
      icon: "ShareIcon",
      formats: [
        {
          id: "linkedin_post",
          name: "LinkedIn Post",
          width: 1200,
          height: 1200,
          ratio: "1:1",
          platform_type: "linkedin_post",
          color: "#0A66C2",
          key: "linkedin",
          cat: "linkedin",
        },
      ],
    },
    {
      id: "resumes",
      label: "Resumes",
      icon: "DocumentIcon",
      formats: [
        {
          id: "resume_cv",
          name: "Resume CV",
          width: 2480,
          height: 3508,
          ratio: "1:1.41",
          platform_type: "resume_a4",
          color: "#6366f1",
          key: "generic",
          cat: "resumes",
        },
      ],
    },
    {
      id: "print",
      label: "Print",
      icon: "PrintIcon",
      formats: [
        {
          id: "poster_a4",
          name: "Poster A4",
          width: 2480,
          height: 3508,
          ratio: "1:1.41",
          platform_type: "poster",
          color: "#f59e0b",
          key: "generic",
          cat: "print",
        },
      ],
    },
    {
      id: "logo",
      label: "Logo",
      icon: "BrushIcon",
      formats: [
        {
          id: "logo_design",
          name: "Logo Design",
          width: 500,
          height: 500,
          ratio: "1:1",
          platform_type: "logo",
          color: "#10b981",
          key: "generic",
          cat: "logo",
        },
      ],
    },
  ],
};
