const subjectsData = [
  {
    id: "gk",
    apiSubject: "General Knowledge",
    name: "General Knowledge",
    icon: "🌍",
    color: "bg-amber-500",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
    categories: [],
    loaded: false,
    loading: false,
  },
  {
    id: "maths",
    apiSubject: "Mathematics", // 👈 Maths ki jagah Mathematics Bhej rahe hain
    name: "Maths",
    icon: "🔢",
    color: "bg-indigo-500",
    badgeColor: "bg-indigo-50 text-indigo-700 border-indigo-200",
    categories: [],
    loaded: false,
    loading: false,
  },
  {
    id: "computer",
    apiSubject: "Computer",
    name: "Computer",
    icon: "💻",
    color: "bg-sky-500",
    badgeColor: "bg-sky-50 text-sky-700 border-sky-200",
    categories: [],
    loaded: false,
    loading: false,
  },
  {
    id: "english",
    apiSubject: "English",
    name: "English",
    icon: "🔤",
    color: "bg-emerald-500",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    categories: [],
    loaded: false,
    loading: false,
  },
  {
    id: "hindi",
    apiSubject: "Hindi",
    name: "Hindi",
    icon: "📚",
    color: "bg-rose-500",
    badgeColor: "bg-rose-50 text-rose-700 border-rose-200",
    categories: [],
    loaded: false,
    loading: false,
  },
];
