export const MUSIC_LIBRARY = [
  {
    id: 1,
    title: "Le jaye tujhe kahan hawayein Lyrics Song",
    filename: "le_jaye_tujhe_kahan_hawayein_lyrics_song.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Jab Harry Met Sejal",
    duration_sec: 19,
    size_mb: 0.55,
    thumbnail: "Jab_Harry_Met_Sejal_.jpg",
  },
  {
    id: 2,
    title: "Le Jaaye Tujhe Kahan Hawayein Hawayein",
    filename: "le_jaaye_tujhe_kahan_hawayein_hawayein.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Jab Harry Met Sejal",
    duration_sec: 46,
    size_mb: 1.25,
    thumbnail: "Jab_Harry_Met_Sejal_.jpg",
  },
  {
    id: 3,
    title: "Sari Duniya Jala Denge B Praak Nee Song",
    filename: "sari_duniya_jala_denge_b_praak_nee_song.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Animal",
    duration_sec: 20,
    size_mb: 0.57,
    thumbnail: "Animal_poster.jpg",
  },
  {
    id: 4,
    title:
      "sari duniya jala denge (official video) b praak | animal movie songs",
    filename:
      "sari_duniya_jala_denge_official_video_b_praak_animal_movie_songs_ranbir_krashmika_m.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Animal",
    duration_sec: 15,
    size_mb: 0.41,
    thumbnail: "Animal_poster.jpg",
  },
  {
    id: 5,
    title: "Pehle Bhi Main Tumse Mila Hoon",
    filename:
      "pehle_bhi_main_tumse_mila_hoon_whatsapp_status_lofi_slowed_song_status.mp3",
    genre: "Bollywood",
    language: "ar",
    movie: "Animal",
    duration_sec: 24,
    size_mb: 0.65,
    thumbnail: "Animal_poster.jpg",
  },
  {
    id: 6,
    title: "Filhaal Song",
    filename:
      "filhaal_2_song_status_teaser_fullscreen_b_praak_akshay_kumar_filhaal_2_whatsapp_status.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Filhaal Song",
    duration_sec: 29,
    size_mb: 0.78,
    thumbnail: "filhal_song_poster_.jpg",
  },
  {
    id: 7,
    title: "Akhiyan Gulab",
    filename: "akhiyan_gulabwhatsapp_status.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Teri Baaton Mein Aisa Uljha Jiya",
    duration_sec: 36,
    size_mb: 1.02,
    thumbnail: "Teri_Baaton_Mein_Aisa_Uljha_Jiya.jpg",
  },
  {
    id: 8,
    title: "O Mahi O Mahi (Status)",
    filename: "o_mahi_o_mahi_song_status_dunki_film_song.mp3",
    genre: "Bollywood",
    language: "ro",
    movie: "Dunki",
    duration_sec: 20,
    size_mb: 0.58,
    thumbnail: "Dunki_poster.jpg",
  },
  {
    id: 9,
    title: "O Mahi O Mahi",
    filename: "o_mahi_o_mahi.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Dunki",
    duration_sec: 15,
    size_mb: 0.42,
    thumbnail: "Dunki_poster.jpg",
  },
  {
    id: 10,
    title: "Chaleya",
    filename: "dive_into_the_magic_of_love_with.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Jawan",
    duration_sec: 10,
    size_mb: 0.31,
    thumbnail: "jawan.png",
  },
  {
    id: 11,
    title: "Ve Kamleya Arijit Singh",
    filename:
      "ve_kamleya_arijit_singh_status_lyrics_status_whatsapp_status.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Rocky Aur Rani Ki Prem Kahani.jpg",
    duration_sec: 11,
    size_mb: 0.3,
    thumbnail: "Rocky_Aur_Rani_Ki_Prem_Kahani.jpg",
  },
  {
    id: 12,
    title: "The Local Train - Choo Lo",
    filename:
      "the_local_train_choo_lo_lyrics_khada_hu_aaj_bhi_wahi_ki_tera_intezaar_hai_song_status.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Aalas_Ka_Pedh.jpg",
    duration_sec: 25,
    size_mb: 0.7,
    thumbnail: "Aalas_Ka_Pedh.jpg",
  },
  {
    id: 13,
    title: "A tale of timeless love",
    filename: "a_tale_of_timeless_love.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Laila Majnu",
    duration_sec: 15,
    size_mb: 0.38,
    thumbnail: "Laila_Majnu.jpg",
  },
  {
    id: 14,
    title: "Coke Studio Bharat",
    filename: "coke_studio_bharat.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Coke Studio",
    duration_sec: 31,
    size_mb: 0.95,
    thumbnail: "Coke_Studio.jpeg",
  },
  {
    id: 15,
    title: "Tauba Tauba",
    filename: "tauba_tauba_hookstep_easiest_tutorial.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Bad Newz",
    duration_sec: 22,
    size_mb: 0.63,
    thumbnail: "Bad_Newz_poster.jpg",
  },
  {
    id: 16,
    title: "Dil Jhoom",
    filename: "dil_jhoom_lyrics_gadar_2_arijit_singh.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Gadar 2",
    duration_sec: 27,
    size_mb: 0.74,
    thumbnail: "Gadar_2_film_poster.jpg",
  },
  {
    id: 17,
    title: "Safarnama",
    filename: "safarnama_song_whatsapp_status.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Tamasha",
    duration_sec: 11,
    size_mb: 0.31,
    thumbnail: "Tamasha_poster.jpg",
  },
  {
    id: 18,
    title: "Kabira Song Lyrics",
    filename: "kabira_song_lyrics_status.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Yeh Jawaani Hai Deewani",
    duration_sec: 12,
    size_mb: 0.32,
    thumbnail: "Yeh-Jawaani-Hai-Deewani.jpg",
  },
  {
    id: 19,
    title: "mann bharya",
    filename: "mann_bharya_status.mp3",
    genre: "Bollywood",
    language: "hi",
    movie: "Shershaah",
    duration_sec: 16,
    size_mb: 0.44,
    thumbnail: "Shershaah_poster.jpeg",
  },
];
