// puzzleData.js - Expanded Category-Wise Puzzle Levels for KidsPaint

const PUZZLE_CATEGORIES = [
  {
    id: "jigsaw",
    name: "Jigsaw Puzzle",
    icon: "🧩",
    levels: [
      {
        id: "jigsaw-lvl-1",
        title: "Happy Toys (4-Grid)",
        grid: 2,
        pieces: [
          {
            id: "j1_1",
            slot: "s1",
            icon: "🧸",
            label: "Teddy",
            bg: "bg-rose-500",
          },
          {
            id: "j1_2",
            slot: "s2",
            icon: "🌸",
            label: "Flower",
            bg: "bg-pink-500",
          },
          {
            id: "j1_3",
            slot: "s3",
            icon: "🎈",
            label: "Balloon",
            bg: "bg-amber-500",
          },
          {
            id: "j1_4",
            slot: "s4",
            icon: "⭐",
            label: "Star",
            bg: "bg-indigo-500",
          },
        ],
      },
      {
        id: "jigsaw-lvl-2",
        title: "Speed Vehicles (4-Grid)",
        grid: 2,
        pieces: [
          {
            id: "j2_1",
            slot: "s1",
            icon: "🚗",
            label: "Red Car",
            bg: "bg-red-500",
          },
          {
            id: "j2_2",
            slot: "s2",
            icon: "🚀",
            label: "Rocket",
            bg: "bg-violet-500",
          },
          {
            id: "j2_3",
            slot: "s3",
            icon: "✈️",
            label: "Airplane",
            bg: "bg-sky-500",
          },
          {
            id: "j2_4",
            slot: "s4",
            icon: "⛵",
            label: "Boat",
            bg: "bg-emerald-500",
          },
        ],
      },
      {
        id: "jigsaw-lvl-3",
        title: "Fruit Basket (4-Grid)",
        grid: 2,
        pieces: [
          {
            id: "j3_1",
            slot: "s1",
            icon: "🍎",
            label: "Apple",
            bg: "bg-red-500",
          },
          {
            id: "j3_2",
            slot: "s2",
            icon: "🍌",
            label: "Banana",
            bg: "bg-amber-400",
          },
          {
            id: "j3_3",
            slot: "s3",
            icon: "🍇",
            label: "Grapes",
            bg: "bg-purple-500",
          },
          {
            id: "j3_4",
            slot: "s4",
            icon: "🍓",
            label: "Berry",
            bg: "bg-pink-500",
          },
        ],
      },
      {
        id: "jigsaw-lvl-4",
        title: "Sweet Treats (4-Grid)",
        grid: 2,
        pieces: [
          {
            id: "j4_1",
            slot: "s1",
            icon: "🍦",
            label: "Ice Cream",
            bg: "bg-cyan-500",
          },
          {
            id: "j4_2",
            slot: "s2",
            icon: "🍩",
            label: "Donut",
            bg: "bg-fuchsia-500",
          },
          {
            id: "j4_3",
            slot: "s3",
            icon: "🧁",
            label: "Cupcake",
            bg: "bg-pink-500",
          },
          {
            id: "j4_4",
            slot: "s4",
            icon: "🍭",
            label: "Lollipop",
            bg: "bg-yellow-500",
          },
        ],
      },
      {
        id: "jigsaw-lvl-5",
        title: "Space Adventure (4-Grid)",
        grid: 2,
        pieces: [
          {
            id: "j5_1",
            slot: "s1",
            icon: "🛸",
            label: "UFO",
            bg: "bg-teal-500",
          },
          {
            id: "j5_2",
            slot: "s2",
            icon: "🪐",
            label: "Saturn",
            bg: "bg-indigo-600",
          },
          {
            id: "j5_3",
            slot: "s3",
            icon: "👨‍🚀",
            label: "Astronaut",
            bg: "bg-blue-500",
          },
          {
            id: "j5_4",
            slot: "s4",
            icon: "☄️",
            label: "Comet",
            bg: "bg-orange-500",
          },
        ],
      },
    ],
  },
  {
    id: "shadow",
    name: "Shadow Match",
    icon: "🧠",
    levels: [
      {
        id: "shadow-lvl-1",
        title: "Wild Animals Match",
        items: [
          { id: "sh_a1", icon: "🦁", name: "Lion", bg: "bg-amber-500" },
          { id: "sh_a2", icon: "🐘", name: "Elephant", bg: "bg-sky-500" },
          { id: "sh_a3", icon: "🐒", name: "Monkey", bg: "bg-orange-500" },
        ],
      },
      {
        id: "shadow-lvl-2",
        title: "Aquatic Life Match",
        items: [
          { id: "sh_f1", icon: "🐠", name: "Fish", bg: "bg-teal-500" },
          { id: "sh_f2", icon: "🐙", name: "Octopus", bg: "bg-rose-500" },
          { id: "sh_f3", icon: "🦀", name: "Crab", bg: "bg-red-500" },
        ],
      },
      {
        id: "shadow-lvl-3",
        title: "Birds & Bugs Match",
        items: [
          { id: "sh_b1", icon: "🦋", name: "Butterfly", bg: "bg-pink-500" },
          { id: "sh_b2", icon: "🦉", name: "Owl", bg: "bg-amber-700" },
          { id: "sh_b3", icon: "🐝", name: "Honeybee", bg: "bg-yellow-400" },
        ],
      },
      {
        id: "shadow-lvl-4",
        title: "Farm Animals Match",
        items: [
          { id: "sh_fm1", icon: "🐮", name: "Cow", bg: "bg-emerald-500" },
          { id: "sh_fm2", icon: "🐴", name: "Horse", bg: "bg-amber-600" },
          { id: "sh_fm3", icon: "🐑", name: "Sheep", bg: "bg-sky-400" },
        ],
      },
      {
        id: "shadow-lvl-5",
        title: "Music & Beats Match",
        items: [
          { id: "sh_m1", icon: "🎸", name: "Guitar", bg: "bg-red-500" },
          { id: "sh_m2", icon: "🥁", name: "Drum", bg: "bg-indigo-500" },
          { id: "sh_m3", icon: "🎺", name: "Trumpet", bg: "bg-yellow-500" },
        ],
      },
    ],
  },
  {
    id: "shapes",
    name: "Shape Matcher",
    icon: "🔷",
    levels: [
      {
        id: "shapes-lvl-1",
        title: "Basic Shapes Match",
        items: [
          {
            id: "shape_1",
            icon: "⭐",
            shapeClass: "rounded-2xl",
            name: "Star",
            bg: "bg-amber-400",
          },
          {
            id: "shape_2",
            icon: "🔵",
            shapeClass: "rounded-full",
            name: "Circle",
            bg: "bg-blue-500",
          },
          {
            id: "shape_3",
            icon: "🔺",
            shapeClass: "rounded-lg",
            name: "Triangle",
            bg: "bg-emerald-500",
          },
          {
            id: "shape_4",
            icon: "🟩",
            shapeClass: "rounded-xl",
            name: "Square",
            bg: "bg-rose-500",
          },
        ],
      },
      {
        id: "shapes-lvl-2",
        title: "Magic Symbols Match",
        items: [
          {
            id: "shape_5",
            icon: "❤️",
            shapeClass: "rounded-2xl",
            name: "Heart",
            bg: "bg-red-500",
          },
          {
            id: "shape_6",
            icon: "💎",
            shapeClass: "rounded-lg",
            name: "Diamond",
            bg: "bg-cyan-400",
          },
          {
            id: "shape_7",
            icon: "🌙",
            shapeClass: "rounded-full",
            name: "Crescent",
            bg: "bg-yellow-300",
          },
          {
            id: "shape_8",
            icon: "⚡",
            shapeClass: "rounded-xl",
            name: "Flash",
            bg: "bg-orange-500",
          },
        ],
      },
      {
        id: "shapes-lvl-3",
        title: "Weather Shapes Match",
        items: [
          {
            id: "shape_9",
            icon: "☀️",
            shapeClass: "rounded-full",
            name: "Sun",
            bg: "bg-amber-500",
          },
          {
            id: "shape_10",
            icon: "☁️",
            shapeClass: "rounded-2xl",
            name: "Cloud",
            bg: "bg-slate-400",
          },
          {
            id: "shape_11",
            icon: "💧",
            shapeClass: "rounded-lg",
            name: "Drop",
            bg: "bg-sky-500",
          },
          {
            id: "shape_12",
            icon: "❄️",
            shapeClass: "rounded-xl",
            name: "Snow",
            bg: "bg-cyan-300",
          },
        ],
      },
      {
        id: "shapes-lvl-4",
        title: "Sports Balls Match",
        items: [
          {
            id: "shape_13",
            icon: "⚽",
            shapeClass: "rounded-full",
            name: "Football",
            bg: "bg-slate-700",
          },
          {
            id: "shape_14",
            icon: "🏀",
            shapeClass: "rounded-full",
            name: "Basketball",
            bg: "bg-orange-600",
          },
          {
            id: "shape_15",
            icon: "🎾",
            shapeClass: "rounded-full",
            name: "Tennis",
            bg: "bg-lime-500",
          },
          {
            id: "shape_16",
            icon: "🎱",
            shapeClass: "rounded-full",
            name: "Pool 8",
            bg: "bg-slate-900",
          },
        ],
      },
    ],
  },
];
