export const TEMPLATE_LIBRARY = [
  {
    meta: {
      templateId: "edu-smart-tips-001",
      title: "Smart Learning Tips",
      category: "Education",
      subcategories: "school",
      tags: ["learning", "tips", "modern"],
      platform_type: "instagram_post_square",
      layoutW: 1080,
      layoutH: 1080,
      thumbnail:
        "https://images.pexels.com/photos/301920/pexels-photo-301920.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 2001,
          background: "#F3F4F6", // Light clean background
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/301920/pexels-photo-301920.jpeg?auto=compress&cs=tinysrgb&w=800",
              left: 540,
              top: 400,
              width: 700,
              height: 500,
              originX: "center",
              originY: "center",
              clipPath: "rounded-rect", // Logic for rounded corners
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "5 TIPS FOR FAST LEARNING",
              left: 540,
              top: 750,
              fontSize: 72,
              fontFamily: "Montserrat",
              fill: "#1F2937",
              textAlign: "center",
              originX: "center",
              width: 900,
              fontWeight: "bold",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Swipe to learn more →",
              left: 540,
              top: 950,
              fontSize: 32,
              fontFamily: "Inter",
              fill: "#6B7280",
              textAlign: "center",
              originX: "center",
              width: 800,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "brand-quote-003",
      title: "Mindset Quote",
      category: "Personal Branding",
      subcategories: "motivation",
      tags: ["quote", "minimal", "twitter"],
      platform_type: "instagram_post_square",
      layoutW: 1080,
      layoutH: 1080,
      thumbnail:
        "https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 4001,
          background: "#FFFFFF",
          objects: [
            {
              role: "image", // Background texture
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress&cs=tinysrgb&w=1080",
              left: 540,
              top: 540,
              width: 1080,
              height: 1080,
              originX: "center",
              originY: "center",
              opacity: 0.1,
            },
            {
              role: "shape", // Quote Box
              type: "rect",
              left: 540,
              top: 540,
              width: 850,
              height: 450,
              fill: "#FFFFFF",
              originX: "center",
              originY: "center",
              shadow: "rgba(0,0,0,0.1) 0px 10px 30px",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "“Success is not final, failure is not fatal.”",
              left: 540,
              top: 520,
              fontSize: 48,
              fontFamily: "Playfair Display",
              fill: "#111111",
              textAlign: "center",
              originX: "center",
              width: 750,
              fontStyle: "italic",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "@yourname",
              left: 540,
              top: 650,
              fontSize: 28,
              fontFamily: "Inter",
              fill: "#3B82F6",
              textAlign: "center",
              originX: "center",
              width: 400,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "tech-minimal-001",
      title: "Digital Growth Tips",
      category: "Education",
      subcategories: "business",
      tags: ["tech", "minimal", "tips"],
      platform_type: "instagram_post_square",
      layoutW: 1080,
      layoutH: 1080,
      thumbnail:
        "https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 5001,
          background: "#FFFFFF",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1000",
              left: 540,
              top: 400,
              width: 1080,
              height: 600,
              originX: "center",
              originY: "center",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "3 WAYS TO SCALE\nYOUR STARTUP",
              left: 50,
              top: 750,
              fontSize: 85,
              fontFamily: "Anton",
              fill: "#1A1A1A",
              textAlign: "left",
              width: 980,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Proven strategies for 2026",
              left: 50,
              top: 960,
              fontSize: 35,
              fontFamily: "Inter",
              fill: "#4B5563",
              textAlign: "left",
              width: 800,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "gym-dark-002",
      title: "Morning Hustle Story",
      category: "Awareness",
      subcategories: "fitness",
      tags: ["gym", "dark", "motivational"],
      platform_type: "instagram_story",
      layoutW: 1080,
      layoutH: 1920,
      thumbnail:
        "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 6001,
          background: "#000000",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=1200",
              left: 540,
              top: 960,
              width: 1080,
              height: 1920,
              originX: "center",
              originY: "center",
              opacity: 0.6,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "NO EXCUSES",
              left: 540,
              top: 850,
              fontSize: 140,
              fontFamily: "Bebas Neue",
              fill: "#FFD700", // Gold Accent
              textAlign: "center",
              originX: "center",
              width: 1000,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "STAY CONSISTENT. STAY HUNGRY.",
              left: 540,
              top: 1020,
              fontSize: 32,
              fontFamily: "Montserrat",
              fill: "#FFFFFF",
              textAlign: "center",
              originX: "center",
              width: 900,
              charSpacing: 100,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "school-creative-003",
      title: "Art Workshop Invite",
      category: "Education",
      subcategories: "school",
      tags: ["creative", "workshop", "kids"],
      platform_type: "instagram_post_square",
      layoutW: 1080,
      layoutH: 1080,
      thumbnail:
        "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 7001,
          background: "#FFF9E6", // Light yellow tint
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=800",
              left: 540,
              top: 350,
              width: 800,
              height: 450,
              originX: "center",
              originY: "center",
              stroke: "#F59E0B",
              strokeWidth: 10,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "BACK TO SCHOOL",
              left: 540,
              top: 680,
              fontSize: 80,
              fontFamily: "Comfortaa",
              fill: "#D97706",
              textAlign: "center",
              originX: "center",
              width: 950,
              fontWeight: "bold",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Join our annual creative session",
              left: 540,
              top: 850,
              fontSize: 40,
              fontFamily: "Quicksand",
              fill: "#1F2937",
              textAlign: "center",
              originX: "center",
              width: 850,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "women-glance-story-004",
      title: "Confident Woman Story",
      category: "Education", // Self-growth education
      subcategories: "personal-development",
      tags: ["women", "confidence", "story", "trending"],
      platform_type: "instagram_story",
      layoutW: 1080,
      layoutH: 1920,
      thumbnail:
        "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 11001,
          background: "#1A1A1A",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              // Ye image face aur personality focus hai
              src: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=1200",
              left: 540,
              top: 960,
              width: 1080,
              height: 1920,
              originX: "center",
              originY: "center",
              opacity: 0.8,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "OWN YOUR",
              left: 540,
              top: 1450,
              fontSize: 110,
              fontFamily: "Bebas Neue",
              fill: "#FFFFFF",
              textAlign: "center",
              originX: "center",
              width: 1000,
              charSpacing: 10,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "CONFIDENCE",
              left: 540,
              top: 1560,
              fontSize: 130,
              fontFamily: "Anton",
              fill: "#F472B6", // Trending Pink accent
              textAlign: "center",
              originX: "center",
              width: 1000,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "You are your own greatest asset.",
              left: 540,
              top: 1700,
              fontSize: 38,
              fontFamily: "Montserrat",
              fill: "#E5E7EB",
              textAlign: "center",
              originX: "center",
              width: 900,
              fontStyle: "italic",
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "women-lifestyle-story-005",
      title: "Elegant Wellness Story",
      category: "Education",
      subcategories: "lifestyle",
      tags: ["women", "aesthetic", "soft", "trending"],
      platform_type: "instagram_story",
      layoutW: 1080,
      layoutH: 1920,
      thumbnail:
        "https://images.pexels.com/photos/3768911/pexels-photo-3768911.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 12001,
          background: "#FDFCF0", // Creamy soft background
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              // Ye image bright, smiling aur face-focus hai
              src: "https://images.pexels.com/photos/3768911/pexels-photo-3768911.jpeg?auto=compress&cs=tinysrgb&w=1200",
              left: 540,
              top: 750,
              width: 900,
              height: 1100,
              originX: "center",
              originY: "center",
              stroke: "#FFFFFF",
              strokeWidth: 15,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Self-Care Sunday",
              left: 540,
              top: 1400,
              fontSize: 90,
              fontFamily: "Pacifico",
              fill: "#8B5E3C", // Deep earthy brown
              textAlign: "center",
              originX: "center",
              width: 1000,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "PRIORITIZE YOUR PEACE",
              left: 540,
              top: 1550,
              fontSize: 45,
              fontFamily: "Montserrat",
              fill: "#A27B5C",
              textAlign: "center",
              originX: "center",
              width: 900,
              charSpacing: 50,
              fontWeight: "bold",
            },
            {
              role: "shape",
              type: "rect",
              left: 540,
              top: 1720,
              width: 400,
              height: 100,
              fill: "#8B5E3C",
              originX: "center",
              originY: "center",
              rx: 50, // Button style rounded corners
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "READ MORE",
              left: 540,
              top: 1710,
              fontSize: 30,
              fontFamily: "Inter",
              fill: "#FFFFFF",
              textAlign: "center",
              originX: "center",
              width: 380,
              fontWeight: "bold",
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "food-fresh-delivery-008",
      title: "Fresh Food Delivery",
      category: "Business",
      subcategories: "e-commerce",
      tags: ["food", "fresh", "delivery", "trending"],
      platform_type: "instagram_story",
      layoutW: 1080,
      layoutH: 1920,
      thumbnail:
        "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 15001,
          background: "#FFFFFF",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              // Verified active link: Fresh vegetables focus
              src: "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=1200",
              left: 540,
              top: 600,
              width: 1080,
              height: 1200,
              originX: "center",
              originY: "center",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "FRESHNESS DELIVERED TO YOUR DOORSTEP",
              left: 540,
              top: 1350,
              fontSize: 80,
              fontFamily: "Anton",
              fill: "#15803D", // Fresh Green
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 950,
              splitByGrapheme: true,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Order today and get 20% off on your first purchase. Healthy living starts here.",
              left: 540,
              top: 1550,
              fontSize: 42,
              fontFamily: "Inter",
              fill: "#374151",
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 900,
              splitByGrapheme: true,
              lineHeight: 1.3,
            },
            {
              role: "shape",
              type: "rect",
              left: 540,
              top: 1750,
              width: 450,
              height: 100,
              fill: "#F59E0B", // Amber button for CTA
              originX: "center",
              originY: "center",
              rx: 50,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "ORDER NOW",
              left: 540,
              top: 1750,
              fontSize: 36,
              fontFamily: "Montserrat",
              fill: "#FFFFFF",
              textAlign: "center",
              originX: "center",
              originY: "center",
              fontWeight: "bold",
              width: 400, // Added width
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "yt-thumb-edu-012",
      title: "Master Class Thumbnail",
      category: "Education",
      platform_type: "youtube_thumbnail",
      layoutW: 1280,
      layoutH: 720,
      thumbnail:
        "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 19001,
          background: "#0F172A",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1280",
              left: 850,
              top: 360,
              width: 800,
              height: 720,
              originX: "center",
              originY: "center",
              opacity: 0.8,
            },
            {
              role: "shape", // Gradient Sticker Style
              type: "rect",
              left: 0,
              top: 0,
              width: 700,
              height: 720,
              fill: "#FF0000",
              originX: "left",
              originY: "top",
              angle: -5,
              skewX: 10,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "LEARN MERN STACK IN 1 HOUR",
              left: 50,
              top: 360,
              fontSize: 80,
              fontFamily: "Anton",
              fill: "#FFFFFF",
              textAlign: "left",
              originY: "center",
              width: 600,
              fontWeight: "bold",
              splitByGrapheme: true,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "fb-awareness-013",
      title: "Community Growth Post",
      category: "Awareness",
      platform_type: "facebook_post",
      layoutW: 1200,
      layoutH: 630,
      thumbnail:
        "https://images.pexels.com/photos/461049/pexels-photo-461049.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 20001,
          background: "#F0F2F5",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/461049/pexels-photo-461049.jpeg?auto=compress&cs=tinysrgb&w=1200",
              left: 600,
              top: 315,
              width: 1200,
              height: 630,
              originX: "center",
              originY: "center",
              opacity: 0.4,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "JOIN OUR LOCAL COMMUNITY",
              left: 600,
              top: 280,
              fontSize: 70,
              fontFamily: "Montserrat",
              fill: "#1877F2",
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 1000,
              fontWeight: "bold",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Together we build a better future. Sign up today!",
              left: 600,
              top: 400,
              fontSize: 35,
              fontFamily: "Inter",
              fill: "#4B5563",
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 900,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "wa-awareness-023",
      title: "Education Awareness Status",
      category: "Awareness",
      subcategories: "school-education",
      tags: ["whatsapp_status", "whatsapp", "education", "tips"],
      platform_type: "whatsapp_status",
      layoutW: 1080,
      layoutH: 1920,
      thumbnail:
        "https://images.pexels.com/photos/256417/pexels-photo-256417.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 30001,
          background: "#0EA5E9",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/256417/pexels-photo-256417.jpeg?auto=compress&cs=tinysrgb&w=1200",
              left: 540,
              top: 600,
              width: 1080,
              height: 1200,
              originX: "center",
              originY: "center",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "DID YOU KNOW?",
              left: 540,
              top: 1350,
              fontSize: 90,
              fontFamily: "Anton",
              fill: "#FFFFFF",
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 1000,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Active learning increases student retention by 70%. Enroll in our 2026 program now!",
              left: 540,
              top: 1550,
              fontSize: 45,
              fontFamily: "Quicksand",
              fill: "#FFFFFF",
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 950,
              splitByGrapheme: true,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "poster-print-024",
      title: "Environmental Awareness Poster",
      category: "Print",
      subcategories: "awareness",
      tags: ["poster_a4", "print", "a4post", "nature"],
      platform_type: "poster",
      layoutW: 2480,
      layoutH: 3508,
      thumbnail:
        "https://images.pexels.com/photos/414837/pexels-photo-414837.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 31001,
          background: "#ECFDF5",
          objects: [
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/414837/pexels-photo-414837.jpeg?auto=compress&cs=tinysrgb&w=2480",
              left: 1240,
              top: 1200,
              width: 2480,
              height: 2400,
              originX: "center",
              originY: "center",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "SAVE THE GREEN PLANET",
              left: 1240,
              top: 2650,
              fontSize: 180,
              fontFamily: "Bebas Neue",
              fill: "#065F46",
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 2200,
              splitByGrapheme: true,
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "A campaign by Siliguri Green Foundation. Join us this Sunday.",
              left: 1240,
              top: 2950,
              fontSize: 70,
              fontFamily: "Inter",
              fill: "#047857",
              textAlign: "center",
              originX: "center",
              originY: "center",
              width: 2000,
              splitByGrapheme: true,
            },
          ],
        },
      ],
    },
  },
  {
    meta: {
      templateId: "res-teacher-abraham-v3-028",
      title: "CBSE Senior Teacher Resume - Abraham",
      category: "Resumes",
      subcategories: "teaching-professional",
      tags: ["resume_cv", "resumea4", "teacher", "school", "cbse"],
      platform_type: "resume_a4",
      layoutW: 2480,
      layoutH: 3508,
      thumbnail:
        "https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=500",
      pages: [
        {
          id: 35001,
          background: "#FFFFFF",
          objects: [
            // Sidebar Decoration
            {
              role: "shape",
              type: "rect",
              left: 0,
              top: 0,
              width: 850,
              height: 3508,
              fill: "#1E293B",
              originX: "left",
              originY: "top",
            },
            // --- HEADER SECTION (Positioned Higher) ---
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "ABRAHAM",
              left: 950,
              top: 250,
              fontSize: 180,
              fontFamily: "Montserrat",
              fill: "#1E293B",
              textAlign: "left",
              width: 1400,
              fontWeight: "bold",
              originY: "top",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "SENIOR COMPUTER SCIENCE & IT EDUCATOR",
              left: 950,
              top: 480,
              fontSize: 48,
              fontFamily: "Inter",
              fill: "#6366F1",
              textAlign: "left",
              width: 1400,
              charSpacing: 40,
              originY: "top",
            },
            // --- SIDEBAR CONTENT ---
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "CONTACT",
              left: 100,
              top: 250,
              fontSize: 65,
              fontFamily: "Montserrat",
              fill: "#38B2AC",
              textAlign: "left",
              width: 650,
              fontWeight: "bold",
              originY: "top",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "📧 abraham.teacher@email.com\n\n📞 +91 90000 00000\n\n📍 Siliguri, West Bengal\n\n🌐 linkedin.com/in/abraham",
              left: 100,
              top: 400,
              fontSize: 38,
              fontFamily: "Inter",
              fill: "#E2E8F0",
              textAlign: "left",
              width: 700,
              lineHeight: 1.8,
              originY: "top",
            },
            // Sidebar Skills (Large Gap)
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "TECHNICAL SKILLS",
              left: 100,
              top: 1100,
              fontSize: 65,
              fontFamily: "Montserrat",
              fill: "#38B2AC",
              textAlign: "left",
              width: 650,
              fontWeight: "bold",
              originY: "top",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "• Python & Java Programming\n• Robotics & Arduino IoT\n• Web Development (MERN)\n• SQL & Database Management\n• AI & Machine Learning Basics",
              left: 100,
              top: 1250,
              fontSize: 38,
              fontFamily: "Inter",
              fill: "#E2E8F0",
              textAlign: "left",
              width: 700,
              lineHeight: 2.2,
              originY: "top",
            },
            // --- MAIN BODY CONTENT ---
            // Profile (Spaced from Header)
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "PROFESSIONAL PROFILE",
              left: 950,
              top: 800,
              fontSize: 65,
              fontFamily: "Montserrat",
              fill: "#1E293B",
              textAlign: "left",
              width: 1400,
              fontWeight: "bold",
              originY: "top",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "Dedicated CBSE Educator with over 10 years of experience in computer science and technology. Expert in developing innovative lesson plans that integrate robotics and STEM, fostering a future-ready learning environment for secondary students.",
              left: 950,
              top: 950,
              fontSize: 40,
              fontFamily: "Inter",
              fill: "#475569",
              textAlign: "left",
              width: 1400,
              lineHeight: 1.6,
              splitByGrapheme: true,
              originY: "top",
            },
            // Work Experience (Large Spacing)
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "WORK EXPERIENCE",
              left: 950,
              top: 1500,
              fontSize: 65,
              fontFamily: "Montserrat",
              fill: "#1E293B",
              textAlign: "left",
              width: 1400,
              fontWeight: "bold",
              originY: "top",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "HOD - Computer Science | Reputed CBSE School\n2018 – Present",
              left: 950,
              top: 1650,
              fontSize: 45,
              fontFamily: "Inter",
              fill: "#0F172A",
              textAlign: "left",
              width: 1400,
              fontWeight: "bold",
              originY: "top",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "• Managed the IT curriculum for secondary and senior secondary wings.\n• Successfully guided students to 100% pass rates in board examinations.\n• Spearheaded the robotics club and represented the school in national expos.",
              left: 950,
              top: 1800,
              fontSize: 40,
              fontFamily: "Inter",
              fill: "#475569",
              textAlign: "left",
              width: 1400,
              lineHeight: 1.8,
              splitByGrapheme: true,
              originY: "top",
            },
            // Academic Background (Large Spacing)
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "ACADEMIC BACKGROUND",
              left: 950,
              top: 2400,
              fontSize: 65,
              fontFamily: "Montserrat",
              fill: "#1E293B",
              textAlign: "left",
              width: 1400,
              fontWeight: "bold",
              originY: "top",
            },
            {
              role: "textbox",
              type: "textbox",
              styles: [],
              text: "B.Tech in Computer Science & Engineering\nMaulana Abul Kalam Azad University | 2013",
              left: 950,
              top: 2550,
              fontSize: 42,
              fontFamily: "Inter",
              fill: "#475569",
              textAlign: "left",
              width: 1400,
              fontWeight: "bold",
              originY: "top",
            },
            // Footer Image
            {
              role: "image",
              type: "image",
              crossOrigin: "anonymous",
              src: "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=800",
              left: 1700,
              top: 3100,
              width: 800,
              height: 500,
              originX: "center",
              originY: "center",
              opacity: 0.1,
            },
          ],
        },
      ],
    },
  },
];

export const TEMPLATE_LIBRARY_MAP = new Map(
  TEMPLATE_LIBRARY.map((t) => [t.meta?.templateId?.trim().toLowerCase(), t]),
);

/**
 * Fast Helper Function
 */
export const getTemplateById = (id) => {
  if (!id) return null;
  return TEMPLATE_LIBRARY_MAP.get(id.trim().toLowerCase()) || null;
};
