// FONT FAMILIES USED IN THIS LIBRARY:
// Arial Black, Georgia, Arial,
// Anton, Bebas Neue, Oswald, Orbitron,
// Caveat, Dancing Script, Lobster, Pacifico, Permanent Marker,
// Inter, Montserrat, Quicksand, Roboto, Comfortaa,
// Cinzel, Playfair Display

export const TEXT_LIBRARY = {
  // 1. BASIC FONTS (System & Categorized)
  fonts: [
    {
      category: "Default Styles",
      items: [
        {
          name: "Heading",
          family: "Arial Black",
          size: 80,
          weight: 900,
          type: "system",
        },
        {
          name: "Subheading",
          family: "Georgia",
          size: 55,
          weight: 400,
          type: "system",
        },
        {
          name: "Body Text",
          family: "Arial",
          size: 40,
          weight: 200,
          type: "system",
        },
      ],
    },
    {
      category: "Display & Bold",
      items: [
        { name: "Anton", family: "Anton", size: 70, weight: 400 },
        { name: "Bebas Neue", family: "Bebas Neue", size: 80, weight: 400 },
        { name: "Oswald", family: "Oswald", size: 55, weight: 700 },
        { name: "Orbitron", family: "Orbitron", size: 55, weight: 900 },
      ],
    },
    {
      category: "Handwriting & Script",
      items: [
        { name: "Caveat", family: "Caveat", size: 60, weight: 400 },
        {
          name: "Dancing Script",
          family: "Dancing Script",
          size: 55,
          weight: 400,
        },
        { name: "Lobster", family: "Lobster", size: 60, weight: 400 },
        { name: "Pacifico", family: "Pacifico", size: 60, weight: 400 },
        {
          name: "Permanent Marker",
          family: "Permanent Marker",
          size: 58,
          weight: 400,
        },
      ],
    },
    {
      category: "Modern Sans",
      items: [
        { name: "Inter", family: "Inter", size: 45, weight: 400 },
        { name: "Montserrat", family: "Montserrat", size: 40, weight: 400 },
        { name: "Quicksand", family: "Quicksand", size: 48, weight: 400 },
        { name: "Roboto", family: "Roboto", size: 45, weight: 400 },
        { name: "Comfortaa", family: "Comfortaa", size: 50, weight: 400 },
      ],
    },
    {
      category: "Classic Serif",
      items: [
        { name: "Cinzel", family: "Cinzel", size: 60, weight: 700 },
        {
          name: "Playfair Display",
          family: "Playfair Display",
          size: 50,
          weight: 400,
        },
      ],
    },
  ],

  // 2. PRE-DESIGNED TEXT COMBINATIONS (Text Styles)
  text_styles: [
    {
      id: "summer-vibes",
      previewName: "Summer Sale",
      category: "Marketing",
      objects: [
        {
          content: "SUMMER",
          fontSize: 80,
          fontWeight: 400,
          fill: "#ff4d4d",
          fontFamily: "Bebas Neue",
          top: -40,
        },
        {
          content: "BIG SALE",
          fontSize: 40,
          fontWeight: 400,
          fill: "#ffcc00",
          fontFamily: "Pacifico",
          top: 15,
          angle: -5,
        },
        {
          content: "UP TO 50% OFF",
          fontSize: 18,
          fontWeight: 700,
          fill: "#ffffff",
          backgroundColor: "#000000",
          fontFamily: "Montserrat",
          top: 60,
          charSpacing: 100,
        },
      ],
    },
    {
      id: "business-minimal",
      previewName: "Corporate",
      category: "Business",
      objects: [
        {
          content: "GROW YOUR",
          fontSize: 14,
          fontWeight: 700,
          fill: "#64748b",
          fontFamily: "Montserrat",
          top: -30,
          charSpacing: 200,
        },
        {
          content: "BUSINESS",
          fontSize: 65,
          fontWeight: 400,
          fill: "#0f172a",
          fontFamily: "Anton",
          top: 15,
        },
        {
          content: "Solutions for tomorrow",
          fontSize: 16,
          fontWeight: 400,
          fill: "#334155",
          fontFamily: "Roboto",
          top: 55,
        },
      ],
    },
    {
      id: "love-romantic",
      previewName: "Romantic",
      category: "Social",
      objects: [
        {
          content: "You & Me",
          fontSize: 70,
          fontWeight: 400,
          fill: "#db2777",
          fontFamily: "Dancing Script",
          top: -10,
        },
        {
          content: "FOREVER ALWAYS",
          fontSize: 12,
          fontWeight: 700,
          fill: "#f472b6",
          fontFamily: "Montserrat",
          top: 40,
          charSpacing: 300,
        },
      ],
    },
    {
      id: "peace-zen",
      previewName: "Mindfulness",
      category: "Aesthetic",
      objects: [
        {
          content: "FIND YOUR",
          fontSize: 15,
          fontWeight: 300,
          fill: "#1e293b",
          fontFamily: "Quicksand",
          top: -35,
          charSpacing: 150,
        },
        {
          content: "Inner Peace",
          fontSize: 50,
          fontWeight: 400,
          fill: "#059669",
          fontFamily: "Caveat",
          top: 5,
        },
        {
          content: "MIND FULLNESS",
          fontSize: 12,
          fontWeight: 700,
          fill: "#64748b",
          fontFamily: "Comfortaa",
          top: 45,
          charSpacing: 200,
        },
      ],
    },
    {
      id: "reels-trending",
      previewName: "Reels POV",
      category: "Social",
      objects: [
        {
          content: "POV:",
          fontSize: 20,
          fontWeight: 900,
          fill: "#ffffff",
          backgroundColor: "#6366f1",
          fontFamily: "Inter",
          top: -45,
        },
        {
          content: "WEEKEND VLOG",
          fontSize: 55,
          fontWeight: 400,
          fill: "#1e293b",
          fontFamily: "Bebas Neue",
          top: 5,
        },
        {
          content: "tap for more",
          fontSize: 14,
          fontWeight: 400,
          fill: "#94a3b8",
          fontFamily: "Pacifico",
          top: 50,
        },
      ],
    },
    {
      id: "neon-night",
      previewName: "Night Life",
      category: "Aesthetic",
      objects: [
        {
          content: "PARTY",
          fontSize: 70,
          fontWeight: 900,
          fill: "#22d3ee",
          fontFamily: "Orbitron",
          top: 0,
          shadow: "0 0 15px rgba(34, 211, 238, 0.8)",
        },
      ],
    },
    {
      id: "dance-party",
      previewName: "Dance Fever",
      category: "Events",
      objects: [
        {
          content: "DANCE",
          fontSize: 80,
          fontWeight: 900,
          fill: "#f472b6",
          fontFamily: "Lobster",
          top: -30,
          angle: -5,
        },
        {
          content: "NIGHT",
          fontSize: 40,
          fontWeight: 400,
          fill: "#ffffff",
          backgroundColor: "#db2777",
          fontFamily: "Montserrat",
          top: 30,
          charSpacing: 150,
        },
      ],
    },
    {
      id: "masti-vibes",
      previewName: "Desi Masti",
      category: "Social",
      objects: [
        {
          content: "Dosto Wali",
          fontSize: 25,
          fontWeight: 400,
          fill: "#f59e0b",
          fontFamily: "Caveat",
          top: -35,
        },
        {
          content: "MASTI",
          fontSize: 75,
          fontWeight: 900,
          fill: "#ef4444",
          fontFamily: "Permanent Marker",
          top: 10,
        },
      ],
    },
    {
      id: "flash-sale",
      previewName: "Flash Sale",
      category: "Marketing",
      objects: [
        {
          content: "FLASH",
          fontSize: 90,
          fontWeight: 400,
          fill: "#000000",
          fontFamily: "Anton",
          top: -20,
        },
        {
          content: "SALE 70%",
          fontSize: 20,
          fontWeight: 700,
          fill: "#ffffff",
          backgroundColor: "#ef4444",
          fontFamily: "Inter",
          top: 45,
          charSpacing: 200,
        },
      ],
    },
    {
      id: "mega-sale-bold",
      previewName: "Mega Sale",
      category: "Marketing",
      objects: [
        {
          content: "BIGGEST",
          fontSize: 22,
          fontWeight: 700,
          fill: "#ffffff",
          backgroundColor: "#000000",
          fontFamily: "Montserrat",
          top: -45,
          charSpacing: 400,
        },
        {
          content: "SALE",
          fontSize: 100,
          fontWeight: 900,
          fill: "#ff4d4d",
          fontFamily: "Anton",
          top: 10,
        },
        {
          content: "UP TO 70% OFF",
          fontSize: 18,
          fontWeight: 700,
          fill: "#000000",
          fontFamily: "Inter",
          top: 65,
          charSpacing: 150,
        },
      ],
    },
    {
      id: "fashion-retail",
      previewName: "New Collection",
      category: "Marketing",
      objects: [
        {
          content: "NEW",
          fontSize: 20,
          fontWeight: 400,
          fill: "#334155",
          fontFamily: "Playfair Display",
          top: -35,
        },
        {
          content: "COLLECTION",
          fontSize: 55,
          fontWeight: 700,
          fill: "#1e293b",
          fontFamily: "Cinzel",
          top: 10,
          charSpacing: 100,
        },
        {
          content: "SHOP NOW",
          fontSize: 14,
          fontWeight: 700,
          fill: "#ffffff",
          backgroundColor: "#1e293b",
          fontFamily: "Montserrat",
          top: 55,
          charSpacing: 300,
        },
      ],
    },

    // --- CATEGORY: SOCIAL & QUOTES ---
    {
      id: "daily-quote",
      previewName: "Elegant Quote",
      category: "Social",
      objects: [
        {
          content: "“",
          fontSize: 120,
          fontWeight: 900,
          fill: "#e2e8f0",
          fontFamily: "Playfair Display",
          top: -30,
        },
        {
          content: "Believe in yourself",
          fontSize: 45,
          fontWeight: 400,
          fill: "#475569",
          fontFamily: "Dancing Script",
          top: 10,
        },
        {
          content: "STAY POSITIVE",
          fontSize: 12,
          fontWeight: 700,
          fill: "#94a3b8",
          fontFamily: "Montserrat",
          top: 50,
          charSpacing: 400,
        },
      ],
    },
    {
      id: "vlog-intro",
      previewName: "Vlog Title",
      category: "Social",
      objects: [
        {
          content: "MY WEEKEND",
          fontSize: 20,
          fontWeight: 900,
          fill: "#ffffff",
          backgroundColor: "#6366f1",
          fontFamily: "Inter",
          top: -35,
        },
        {
          content: "VLOG",
          fontSize: 85,
          fontWeight: 400,
          fill: "#1e293b",
          fontFamily: "Bebas Neue",
          top: 15,
        },
      ],
    },

    // --- CATEGORY: BUSINESS & CORPORATE ---
    {
      id: "corporate-clean",
      previewName: "Modern Business",
      category: "Business",
      objects: [
        {
          content: "WE ARE",
          fontSize: 14,
          fontWeight: 700,
          fill: "#6366f1",
          fontFamily: "Montserrat",
          top: -30,
          charSpacing: 300,
        },
        {
          content: "HIRING",
          fontSize: 70,
          fontWeight: 900,
          fill: "#1e293b",
          fontFamily: "Oswald",
          top: 15,
        },
        {
          content: "Join our creative team",
          fontSize: 16,
          fontWeight: 400,
          fill: "#64748b",
          fontFamily: "Roboto",
          top: 55,
        },
      ],
    },
    {
      id: "tech-minimal",
      previewName: "Tech Event",
      category: "Business",
      objects: [
        {
          content: "FUTURE",
          fontSize: 80,
          fontWeight: 900,
          fill: "#0ea5e9",
          fontFamily: "Orbitron",
          top: -10,
        },
        {
          content: "CONFERENCE 2026",
          fontSize: 14,
          fontWeight: 700,
          fill: "#0f172a",
          fontFamily: "Inter",
          top: 45,
          charSpacing: 500,
        },
      ],
    },

    // --- CATEGORY: LIFESTYLE & FOOD ---
    {
      id: "organic-food",
      previewName: "Healthy Food",
      category: "Food",
      objects: [
        {
          content: "100% NATURAL",
          fontSize: 12,
          fontWeight: 700,
          fill: "#059669",
          fontFamily: "Montserrat",
          top: -40,
          charSpacing: 250,
        },
        {
          content: "Organic",
          fontSize: 70,
          fontWeight: 400,
          fill: "#065f46",
          fontFamily: "Caveat",
          top: 5,
        },
        {
          content: "FRESH FROM FARM",
          fontSize: 14,
          fontWeight: 400,
          fill: "#34495e",
          fontFamily: "Comfortaa",
          top: 50,
        },
      ],
    },
    {
      id: "coffee-house",
      previewName: "Coffee Shop",
      category: "Food",
      objects: [
        {
          content: "BREWED",
          fontSize: 15,
          fontWeight: 400,
          fill: "#78350f",
          fontFamily: "Oswald",
          top: -30,
          charSpacing: 200,
        },
        {
          content: "Coffee",
          fontSize: 65,
          fontWeight: 400,
          fill: "#451a03",
          fontFamily: "Pacifico",
          top: 10,
        },
        {
          content: "STAY AWAKE",
          fontSize: 10,
          fontWeight: 700,
          fill: "#92400e",
          fontFamily: "Montserrat",
          top: 45,
          charSpacing: 400,
        },
      ],
    },

    {
      id: "party-time",
      previewName: "Birthday Party",
      category: "Events",
      objects: [
        {
          content: "BIRTHDAY",
          fontSize: 25,
          fontWeight: 400,
          fill: "#f472b6",
          fontFamily: "Comfortaa",
          top: -30,
        },
        {
          content: "PARTY",
          fontSize: 70,
          fontWeight: 400,
          fill: "#db2777",
          fontFamily: "Lobster",
          top: 15,
          angle: -3,
        },
      ],
    },
    {
      id: "back-to-school",
      previewName: "Back to School",
      category: "Education",
      objects: [
        {
          content: "BACK TO",
          fontSize: 20,
          fontWeight: 400,
          fill: "#64748b",
          fontFamily: "Comfortaa",
          top: -40,
          charSpacing: 100,
        },
        {
          content: "SCHOOL",
          fontSize: 65,
          fontWeight: 400,
          fill: "#3b82f6",
          fontFamily: "Bebas Neue",
          top: 10,
        },
        {
          content: "Class of 2026",
          fontSize: 22,
          fontWeight: 400,
          fill: "#10b981",
          fontFamily: "Dancing Script",
          top: 55,
        },
      ],
    },
    {
      id: "business-summit",
      previewName: "Tech Summit",
      category: "Business",
      objects: [
        {
          content: "GLOBAL BUSINESS",
          fontSize: 12,
          fontWeight: 700,
          fill: "#94a3b8",
          fontFamily: "Montserrat",
          top: -45,
          charSpacing: 400,
        },
        {
          content: "SUMMIT",
          fontSize: 60,
          fontWeight: 700,
          fill: "#1e293b",
          fontFamily: "Playfair Display",
          top: 5,
        },
        {
          content: "2026",
          fontSize: 50,
          fontWeight: 900,
          fill: "#6366f1",
          fontFamily: "Orbitron",
          top: 60,
          opacity: 0.2,
        },
      ],
    },
    {
      id: "foodie-hub",
      previewName: "Tasty Food",
      category: "Food",
      objects: [
        {
          content: "DELICIOUS",
          fontSize: 18,
          fontWeight: 700,
          fill: "#f59e0b",
          fontFamily: "Montserrat",
          top: -40,
          charSpacing: 200,
        },
        {
          content: "Burger Hub",
          fontSize: 60,
          fontWeight: 400,
          fill: "#b91c1c",
          fontFamily: "Pacifico",
          top: 10,
        },
      ],
    },
  ],
};
